package fr.anatom3000.gwwhit.registry;

import fr.anatom3000.gwwhit.materials.amader.AmaderRoot;
import fr.anatom3000.gwwhit.materials.anaksox.AnaksoxRoot;
import fr.anatom3000.gwwhit.materials.aqyqyf.AqyqyfRoot;
import fr.anatom3000.gwwhit.materials.asymcof.AsymcofRoot;
import fr.anatom3000.gwwhit.materials.baqi.BaqiRoot;
import fr.anatom3000.gwwhit.materials.botud.BotudRoot;
import fr.anatom3000.gwwhit.materials.cojos.CojosRoot;
import fr.anatom3000.gwwhit.materials.dytap.DytapRoot;
import fr.anatom3000.gwwhit.materials.ebeqir.EbeqirRoot;
import fr.anatom3000.gwwhit.materials.ecywygs.EcywygsRoot;
import fr.anatom3000.gwwhit.materials.emilamd.EmilamdRoot;
import fr.anatom3000.gwwhit.materials.emogy.EmogyRoot;
import fr.anatom3000.gwwhit.materials.emussazr.EmussazrRoot;
import fr.anatom3000.gwwhit.materials.exuzi.ExuziRoot;
import fr.anatom3000.gwwhit.materials.folso.FolsoRoot;
import fr.anatom3000.gwwhit.materials.foqepm.FoqepmRoot;
import fr.anatom3000.gwwhit.materials.fucox.FucoxRoot;
import fr.anatom3000.gwwhit.materials.fydif.FydifRoot;
import fr.anatom3000.gwwhit.materials.fyfat.FyfatRoot;
import fr.anatom3000.gwwhit.materials.garar.GararRoot;
import fr.anatom3000.gwwhit.materials.gigyh.GigyhRoot;
import fr.anatom3000.gwwhit.materials.giry.GiryRoot;
import fr.anatom3000.gwwhit.materials.gycu.GycuRoot;
import fr.anatom3000.gwwhit.materials.hoke.HokeRoot;
import fr.anatom3000.gwwhit.materials.hugom.HugomRoot;
import fr.anatom3000.gwwhit.materials.icawlu.IcawluRoot;
import fr.anatom3000.gwwhit.materials.igekez.IgekezRoot;
import fr.anatom3000.gwwhit.materials.ijyqbag.IjyqbagRoot;
import fr.anatom3000.gwwhit.materials.ikaqajc.IkaqajcRoot;
import fr.anatom3000.gwwhit.materials.ipacyk.IpacykRoot;
import fr.anatom3000.gwwhit.materials.iqecoln.IqecolnRoot;
import fr.anatom3000.gwwhit.materials.iqola.IqolaRoot;
import fr.anatom3000.gwwhit.materials.izymam.IzymamRoot;
import fr.anatom3000.gwwhit.materials.jipna.JipnaRoot;
import fr.anatom3000.gwwhit.materials.kigys.KigysRoot;
import fr.anatom3000.gwwhit.materials.kuqoc.KuqocRoot;
import fr.anatom3000.gwwhit.materials.kuzidb.KuzidbRoot;
import fr.anatom3000.gwwhit.materials.lezdor.LezdorRoot;
import fr.anatom3000.gwwhit.materials.lisluq.LisluqRoot;
import fr.anatom3000.gwwhit.materials.loded.LodedRoot;
import fr.anatom3000.gwwhit.materials.lotih.LotihRoot;
import fr.anatom3000.gwwhit.materials.luqysk.LuqyskRoot;
import fr.anatom3000.gwwhit.materials.lysum.LysumRoot;
import fr.anatom3000.gwwhit.materials.lywyg.LywygRoot;
import fr.anatom3000.gwwhit.materials.mafab.MafabRoot;
import fr.anatom3000.gwwhit.materials.mejesh.MejeshRoot;
import fr.anatom3000.gwwhit.materials.mudatb.MudatbRoot;
import fr.anatom3000.gwwhit.materials.nafxa.NafxaRoot;
import fr.anatom3000.gwwhit.materials.nefyf.NefyfRoot;
import fr.anatom3000.gwwhit.materials.nejun.NejunRoot;
import fr.anatom3000.gwwhit.materials.neqaw.NeqawRoot;
import fr.anatom3000.gwwhit.materials.nizuzc.NizuzcRoot;
import fr.anatom3000.gwwhit.materials.notic.NoticRoot;
import fr.anatom3000.gwwhit.materials.nugo.NugoRoot;
import fr.anatom3000.gwwhit.materials.obaseh.ObasehRoot;
import fr.anatom3000.gwwhit.materials.obohylp.ObohylpRoot;
import fr.anatom3000.gwwhit.materials.obuxan.ObuxanRoot;
import fr.anatom3000.gwwhit.materials.ohyxfu.OhyxfuRoot;
import fr.anatom3000.gwwhit.materials.opomfam.OpomfamRoot;
import fr.anatom3000.gwwhit.materials.oquge.OqugeRoot;
import fr.anatom3000.gwwhit.materials.otakag.OtakagRoot;
import fr.anatom3000.gwwhit.materials.pecced.PeccedRoot;
import fr.anatom3000.gwwhit.materials.peqy.PeqyRoot;
import fr.anatom3000.gwwhit.materials.ratfyf.RatfyfRoot;
import fr.anatom3000.gwwhit.materials.renu.RenuRoot;
import fr.anatom3000.gwwhit.materials.rydyrp.RydyrpRoot;
import fr.anatom3000.gwwhit.materials.ryqo.RyqoRoot;
import fr.anatom3000.gwwhit.materials.senuz.SenuzRoot;
import fr.anatom3000.gwwhit.materials.sijtyw.SijtywRoot;
import fr.anatom3000.gwwhit.materials.silo.SiloRoot;
import fr.anatom3000.gwwhit.materials.soneg.SonegRoot;
import fr.anatom3000.gwwhit.materials.sushehn.SushehnRoot;
import fr.anatom3000.gwwhit.materials.suwow.SuwowRoot;
import fr.anatom3000.gwwhit.materials.tefa.TefaRoot;
import fr.anatom3000.gwwhit.materials.tesxes.TesxesRoot;
import fr.anatom3000.gwwhit.materials.tetus.TetusRoot;
import fr.anatom3000.gwwhit.materials.tidziq.TidziqRoot;
import fr.anatom3000.gwwhit.materials.tifut.TifutRoot;
import fr.anatom3000.gwwhit.materials.tugo.TugoRoot;
import fr.anatom3000.gwwhit.materials.tushih.TushihRoot;
import fr.anatom3000.gwwhit.materials.uberteg.UbertegRoot;
import fr.anatom3000.gwwhit.materials.uhyqol.UhyqolRoot;
import fr.anatom3000.gwwhit.materials.umaboz.UmabozRoot;
import fr.anatom3000.gwwhit.materials.uruwogq.UruwogqRoot;
import fr.anatom3000.gwwhit.materials.uwalusq.UwalusqRoot;
import fr.anatom3000.gwwhit.materials.uwaplok.UwaplokRoot;
import fr.anatom3000.gwwhit.materials.uwygan.UwyganRoot;
import fr.anatom3000.gwwhit.materials.uxurup.UxurupRoot;
import fr.anatom3000.gwwhit.materials.wekmal.WekmalRoot;
import fr.anatom3000.gwwhit.materials.wemhec.WemhecRoot;
import fr.anatom3000.gwwhit.materials.wuhitd.WuhitdRoot;
import fr.anatom3000.gwwhit.materials.xugaw.XugawRoot;
import fr.anatom3000.gwwhit.materials.yfikal.YfikalRoot;
import fr.anatom3000.gwwhit.materials.yjosok.YjosokRoot;
import fr.anatom3000.gwwhit.materials.yjotceh.YjotcehRoot;
import fr.anatom3000.gwwhit.materials.yqubef.YqubefRoot;
import fr.anatom3000.gwwhit.materials.ywosduk.YwosdukRoot;
import fr.anatom3000.gwwhit.materials.zawuf.ZawufRoot;
import fr.anatom3000.gwwhit.materials.zytu.ZytuRoot;
import fr.anatom3000.gwwhit.materials.zytutb.ZytutbRoot;

public class NewMaterials {
public static final YwosdukRoot ywosdukRoot = new YwosdukRoot();
public static final KuzidbRoot kuzidbRoot = new KuzidbRoot();
public static final NejunRoot nejunRoot = new NejunRoot();
public static final LezdorRoot lezdorRoot = new LezdorRoot();
public static final EcywygsRoot ecywygsRoot = new EcywygsRoot();
public static final SiloRoot siloRoot = new SiloRoot();
public static final UwyganRoot uwyganRoot = new UwyganRoot();
public static final FolsoRoot folsoRoot = new FolsoRoot();
public static final YjotcehRoot yjotcehRoot = new YjotcehRoot();
public static final BaqiRoot baqiRoot = new BaqiRoot();
public static final HugomRoot hugomRoot = new HugomRoot();
public static final UruwogqRoot uruwogqRoot = new UruwogqRoot();
public static final OpomfamRoot opomfamRoot = new OpomfamRoot();
public static final IqolaRoot iqolaRoot = new IqolaRoot();
public static final ZawufRoot zawufRoot = new ZawufRoot();
public static final IjyqbagRoot ijyqbagRoot = new IjyqbagRoot();
public static final UwaplokRoot uwaplokRoot = new UwaplokRoot();
public static final EbeqirRoot ebeqirRoot = new EbeqirRoot();
public static final MudatbRoot mudatbRoot = new MudatbRoot();
public static final TugoRoot tugoRoot = new TugoRoot();
public static final AnaksoxRoot anaksoxRoot = new AnaksoxRoot();
public static final UhyqolRoot uhyqolRoot = new UhyqolRoot();
public static final RydyrpRoot rydyrpRoot = new RydyrpRoot();
public static final NafxaRoot nafxaRoot = new NafxaRoot();
public static final XugawRoot xugawRoot = new XugawRoot();
public static final AsymcofRoot asymcofRoot = new AsymcofRoot();
public static final SijtywRoot sijtywRoot = new SijtywRoot();
public static final IgekezRoot igekezRoot = new IgekezRoot();
public static final EmogyRoot emogyRoot = new EmogyRoot();
public static final BotudRoot botudRoot = new BotudRoot();
public static final RenuRoot renuRoot = new RenuRoot();
public static final IkaqajcRoot ikaqajcRoot = new IkaqajcRoot();
public static final LotihRoot lotihRoot = new LotihRoot();
public static final TushihRoot tushihRoot = new TushihRoot();
public static final GiryRoot giryRoot = new GiryRoot();
public static final NizuzcRoot nizuzcRoot = new NizuzcRoot();
public static final UmabozRoot umabozRoot = new UmabozRoot();
public static final LywygRoot lywygRoot = new LywygRoot();
public static final JipnaRoot jipnaRoot = new JipnaRoot();
public static final LysumRoot lysumRoot = new LysumRoot();
public static final FucoxRoot fucoxRoot = new FucoxRoot();
public static final OhyxfuRoot ohyxfuRoot = new OhyxfuRoot();
public static final YjosokRoot yjosokRoot = new YjosokRoot();
public static final TetusRoot tetusRoot = new TetusRoot();
public static final NefyfRoot nefyfRoot = new NefyfRoot();
public static final GararRoot gararRoot = new GararRoot();
public static final PeccedRoot peccedRoot = new PeccedRoot();
public static final UxurupRoot uxurupRoot = new UxurupRoot();
public static final RatfyfRoot ratfyfRoot = new RatfyfRoot();
public static final ZytuRoot zytuRoot = new ZytuRoot();
public static final SenuzRoot senuzRoot = new SenuzRoot();
public static final FyfatRoot fyfatRoot = new FyfatRoot();
public static final TesxesRoot tesxesRoot = new TesxesRoot();
public static final IqecolnRoot iqecolnRoot = new IqecolnRoot();
public static final CojosRoot cojosRoot = new CojosRoot();
public static final MafabRoot mafabRoot = new MafabRoot();
public static final OtakagRoot otakagRoot = new OtakagRoot();
public static final TefaRoot tefaRoot = new TefaRoot();
public static final AmaderRoot amaderRoot = new AmaderRoot();
public static final NeqawRoot neqawRoot = new NeqawRoot();
public static final DytapRoot dytapRoot = new DytapRoot();
public static final NugoRoot nugoRoot = new NugoRoot();
public static final LodedRoot lodedRoot = new LodedRoot();
public static final OqugeRoot oqugeRoot = new OqugeRoot();
public static final NoticRoot noticRoot = new NoticRoot();
public static final GigyhRoot gigyhRoot = new GigyhRoot();
public static final FoqepmRoot foqepmRoot = new FoqepmRoot();
public static final SuwowRoot suwowRoot = new SuwowRoot();
public static final MejeshRoot mejeshRoot = new MejeshRoot();
public static final LuqyskRoot luqyskRoot = new LuqyskRoot();
public static final KigysRoot kigysRoot = new KigysRoot();
public static final IpacykRoot ipacykRoot = new IpacykRoot();
public static final ExuziRoot exuziRoot = new ExuziRoot();
public static final ObohylpRoot obohylpRoot = new ObohylpRoot();
public static final AqyqyfRoot aqyqyfRoot = new AqyqyfRoot();
public static final SonegRoot sonegRoot = new SonegRoot();
public static final IzymamRoot izymamRoot = new IzymamRoot();
public static final EmilamdRoot emilamdRoot = new EmilamdRoot();
public static final IcawluRoot icawluRoot = new IcawluRoot();
public static final ObuxanRoot obuxanRoot = new ObuxanRoot();
public static final WemhecRoot wemhecRoot = new WemhecRoot();
public static final GycuRoot gycuRoot = new GycuRoot();
public static final TidziqRoot tidziqRoot = new TidziqRoot();
public static final TifutRoot tifutRoot = new TifutRoot();
public static final WuhitdRoot wuhitdRoot = new WuhitdRoot();
public static final PeqyRoot peqyRoot = new PeqyRoot();
public static final KuqocRoot kuqocRoot = new KuqocRoot();
public static final HokeRoot hokeRoot = new HokeRoot();
public static final ZytutbRoot zytutbRoot = new ZytutbRoot();
public static final YqubefRoot yqubefRoot = new YqubefRoot();
public static final FydifRoot fydifRoot = new FydifRoot();
public static final YfikalRoot yfikalRoot = new YfikalRoot();
public static final UbertegRoot ubertegRoot = new UbertegRoot();
public static final UwalusqRoot uwalusqRoot = new UwalusqRoot();
public static final RyqoRoot ryqoRoot = new RyqoRoot();
public static final WekmalRoot wekmalRoot = new WekmalRoot();
public static final ObasehRoot obasehRoot = new ObasehRoot();
public static final LisluqRoot lisluqRoot = new LisluqRoot();
public static final SushehnRoot sushehnRoot = new SushehnRoot();
public static final EmussazrRoot emussazrRoot = new EmussazrRoot();

public static void onInitialize() {
    ywosdukRoot.onInitialize();
    kuzidbRoot.onInitialize();
    nejunRoot.onInitialize();
    lezdorRoot.onInitialize();
    ecywygsRoot.onInitialize();
    siloRoot.onInitialize();
    uwyganRoot.onInitialize();
    folsoRoot.onInitialize();
    yjotcehRoot.onInitialize();
    baqiRoot.onInitialize();
    hugomRoot.onInitialize();
    uruwogqRoot.onInitialize();
    opomfamRoot.onInitialize();
    iqolaRoot.onInitialize();
    zawufRoot.onInitialize();
    ijyqbagRoot.onInitialize();
    uwaplokRoot.onInitialize();
    ebeqirRoot.onInitialize();
    mudatbRoot.onInitialize();
    tugoRoot.onInitialize();
    anaksoxRoot.onInitialize();
    uhyqolRoot.onInitialize();
    rydyrpRoot.onInitialize();
    nafxaRoot.onInitialize();
    xugawRoot.onInitialize();
    asymcofRoot.onInitialize();
    sijtywRoot.onInitialize();
    igekezRoot.onInitialize();
    emogyRoot.onInitialize();
    botudRoot.onInitialize();
    renuRoot.onInitialize();
    ikaqajcRoot.onInitialize();
    lotihRoot.onInitialize();
    tushihRoot.onInitialize();
    giryRoot.onInitialize();
    nizuzcRoot.onInitialize();
    umabozRoot.onInitialize();
    lywygRoot.onInitialize();
    jipnaRoot.onInitialize();
    lysumRoot.onInitialize();
    fucoxRoot.onInitialize();
    ohyxfuRoot.onInitialize();
    yjosokRoot.onInitialize();
    tetusRoot.onInitialize();
    nefyfRoot.onInitialize();
    gararRoot.onInitialize();
    peccedRoot.onInitialize();
    uxurupRoot.onInitialize();
    ratfyfRoot.onInitialize();
    zytuRoot.onInitialize();
    senuzRoot.onInitialize();
    fyfatRoot.onInitialize();
    tesxesRoot.onInitialize();
    iqecolnRoot.onInitialize();
    cojosRoot.onInitialize();
    mafabRoot.onInitialize();
    otakagRoot.onInitialize();
    tefaRoot.onInitialize();
    amaderRoot.onInitialize();
    neqawRoot.onInitialize();
    dytapRoot.onInitialize();
    nugoRoot.onInitialize();
    lodedRoot.onInitialize();
    oqugeRoot.onInitialize();
    noticRoot.onInitialize();
    gigyhRoot.onInitialize();
    foqepmRoot.onInitialize();
    suwowRoot.onInitialize();
    mejeshRoot.onInitialize();
    luqyskRoot.onInitialize();
    kigysRoot.onInitialize();
    ipacykRoot.onInitialize();
    exuziRoot.onInitialize();
    obohylpRoot.onInitialize();
    aqyqyfRoot.onInitialize();
    sonegRoot.onInitialize();
    izymamRoot.onInitialize();
    emilamdRoot.onInitialize();
    icawluRoot.onInitialize();
    obuxanRoot.onInitialize();
    wemhecRoot.onInitialize();
    gycuRoot.onInitialize();
    tidziqRoot.onInitialize();
    tifutRoot.onInitialize();
    wuhitdRoot.onInitialize();
    peqyRoot.onInitialize();
    kuqocRoot.onInitialize();
    hokeRoot.onInitialize();
    zytutbRoot.onInitialize();
    yqubefRoot.onInitialize();
    fydifRoot.onInitialize();
    yfikalRoot.onInitialize();
    ubertegRoot.onInitialize();
    uwalusqRoot.onInitialize();
    ryqoRoot.onInitialize();
    wekmalRoot.onInitialize();
    obasehRoot.onInitialize();
    lisluqRoot.onInitialize();
    sushehnRoot.onInitialize();
    emussazrRoot.onInitialize();
}

public static void onInitializeClient() {
    ywosdukRoot.onInitializeClient();
    kuzidbRoot.onInitializeClient();
    nejunRoot.onInitializeClient();
    lezdorRoot.onInitializeClient();
    ecywygsRoot.onInitializeClient();
    siloRoot.onInitializeClient();
    uwyganRoot.onInitializeClient();
    folsoRoot.onInitializeClient();
    yjotcehRoot.onInitializeClient();
    baqiRoot.onInitializeClient();
    hugomRoot.onInitializeClient();
    uruwogqRoot.onInitializeClient();
    opomfamRoot.onInitializeClient();
    iqolaRoot.onInitializeClient();
    zawufRoot.onInitializeClient();
    ijyqbagRoot.onInitializeClient();
    uwaplokRoot.onInitializeClient();
    ebeqirRoot.onInitializeClient();
    mudatbRoot.onInitializeClient();
    tugoRoot.onInitializeClient();
    anaksoxRoot.onInitializeClient();
    uhyqolRoot.onInitializeClient();
    rydyrpRoot.onInitializeClient();
    nafxaRoot.onInitializeClient();
    xugawRoot.onInitializeClient();
    asymcofRoot.onInitializeClient();
    sijtywRoot.onInitializeClient();
    igekezRoot.onInitializeClient();
    emogyRoot.onInitializeClient();
    botudRoot.onInitializeClient();
    renuRoot.onInitializeClient();
    ikaqajcRoot.onInitializeClient();
    lotihRoot.onInitializeClient();
    tushihRoot.onInitializeClient();
    giryRoot.onInitializeClient();
    nizuzcRoot.onInitializeClient();
    umabozRoot.onInitializeClient();
    lywygRoot.onInitializeClient();
    jipnaRoot.onInitializeClient();
    lysumRoot.onInitializeClient();
    fucoxRoot.onInitializeClient();
    ohyxfuRoot.onInitializeClient();
    yjosokRoot.onInitializeClient();
    tetusRoot.onInitializeClient();
    nefyfRoot.onInitializeClient();
    gararRoot.onInitializeClient();
    peccedRoot.onInitializeClient();
    uxurupRoot.onInitializeClient();
    ratfyfRoot.onInitializeClient();
    zytuRoot.onInitializeClient();
    senuzRoot.onInitializeClient();
    fyfatRoot.onInitializeClient();
    tesxesRoot.onInitializeClient();
    iqecolnRoot.onInitializeClient();
    cojosRoot.onInitializeClient();
    mafabRoot.onInitializeClient();
    otakagRoot.onInitializeClient();
    tefaRoot.onInitializeClient();
    amaderRoot.onInitializeClient();
    neqawRoot.onInitializeClient();
    dytapRoot.onInitializeClient();
    nugoRoot.onInitializeClient();
    lodedRoot.onInitializeClient();
    oqugeRoot.onInitializeClient();
    noticRoot.onInitializeClient();
    gigyhRoot.onInitializeClient();
    foqepmRoot.onInitializeClient();
    suwowRoot.onInitializeClient();
    mejeshRoot.onInitializeClient();
    luqyskRoot.onInitializeClient();
    kigysRoot.onInitializeClient();
    ipacykRoot.onInitializeClient();
    exuziRoot.onInitializeClient();
    obohylpRoot.onInitializeClient();
    aqyqyfRoot.onInitializeClient();
    sonegRoot.onInitializeClient();
    izymamRoot.onInitializeClient();
    emilamdRoot.onInitializeClient();
    icawluRoot.onInitializeClient();
    obuxanRoot.onInitializeClient();
    wemhecRoot.onInitializeClient();
    gycuRoot.onInitializeClient();
    tidziqRoot.onInitializeClient();
    tifutRoot.onInitializeClient();
    wuhitdRoot.onInitializeClient();
    peqyRoot.onInitializeClient();
    kuqocRoot.onInitializeClient();
    hokeRoot.onInitializeClient();
    zytutbRoot.onInitializeClient();
    yqubefRoot.onInitializeClient();
    fydifRoot.onInitializeClient();
    yfikalRoot.onInitializeClient();
    ubertegRoot.onInitializeClient();
    uwalusqRoot.onInitializeClient();
    ryqoRoot.onInitializeClient();
    wekmalRoot.onInitializeClient();
    obasehRoot.onInitializeClient();
    lisluqRoot.onInitializeClient();
    sushehnRoot.onInitializeClient();
    emussazrRoot.onInitializeClient();
}
}